### ISSUE TITLE
mmcv，pytorch，cuda

### ISSUE THREAD

**Issue by pll000** [zhyx12/CRCo#1]
Dear author
I really enjoy the work you do and would like to take a run on your code
Can you provide me with the runtime environment, especially the mmcv and corresponding Pytorch and Cuda versions

**Comment by zhyx12** [comment]
Thanks for your interest in our work. Some library versions are shown below:
cuda		11.3
torch		1.10.0
torchvision	0.11.0
mmcv-full	1.4.0
mmcls		0.18.0
